apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: terrain
build:
  artifacts:
    - image: harbor.cyverse.org/de/terrain
      platforms:
        - "linux/amd64"
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/terrain.yml
