apiVersion: apps/v1
kind: Deployment
metadata:
  name: terrain
spec:
  replicas: 2
  selector:
    matchLabels:
      de-app: terrain
  template:
    metadata:
      labels:
        de-app: terrain
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: de-app
                operator: In
                values:
                - terrain
            topologyKey: kubernetes.io/hostname
      restartPolicy: Always
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: timezone
          configMap:
            name: timezone
            items:
              - key: timezone
                path: timezone
        - name: signing-keys
          secret:
            secretName: signing-keys
            items:
              - key: private-key.pem
                path: private-key.pem
                mode: 0644

              - key: public-key.pem
                path: public-key.pem
                mode: 0644

              - key: QApubkey.pem
                path: accepted_keys/QApubkey.pem
                mode: 0644

              - key: apim_staging.pub
                path: accepted_keys/apim_staging.pub
                mode: 0644

              - key: legfed-pubkey.pem
                path: accepted_keys/legfed-pubkey.pem
                mode: 0644

              - key: mirrors.pem
                path: accepted_keys/mirrors.pem
                mode: 0644

              - key: peanutbase-pubkey.pem
                path: accepted_keys/peanutbase-pubkey.pem
                mode: 0644

              - key: projects-pubkey.pem
                path: accepted_keys/project-pubkey.pem
                mode: 0644
        - name: service-configs
          secret:
            secretName: service-configs
            items:
              - key: terrain.properties
                path: terrain.properties
      containers:
      - name: terrain
        image: harbor.cyverse.org/de/terrain
        resources:
          requests:
            cpu: "320m"
            memory: "1Gi"
          limits:
            cpu: "3000m"
            memory: "3Gi"
        args:
          - --config
          - /etc/iplant/de/terrain.properties
        volumeMounts:
          - name: signing-keys
            mountPath: /etc/iplant/crypto
            readOnly: true
          - name: localtime
            mountPath: /etc/localtime
            readOnly: true
          - name: timezone
            mountPath: /etc/timezone
            subPath: timezone
          - name: service-configs
            mountPath: /etc/iplant/de
            readOnly: true
        env:
          - name: JAVA_TOOL_OPTIONS
            valueFrom:
              configMapKeyRef:
                name: java-tool-options
                key: high
        ports:
          - name: listen-port
            containerPort: 60000
        livenessProbe:
          httpGet:
            path: /
            port: 60000
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 60000
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: terrain
spec:
  selector:
    de-app: terrain
  ports:
    - protocol: TCP
      port: 80
      targetPort: listen-port
